cwd = getwd()
setwdNew("run_examples")
devtools::run_examples()
setwd(cwd)
ezSystem("rm -fr ./run_examples")
remove1 = system.file("DESCRIPTION_head", package="ezRun", mustWork=TRUE)
remove2 = system.file("extdata/genes.bed", package="ezRun", mustWork=TRUE)
remove3 = system.file("extdata/genesWithPrespliced.gtf", package="ezRun", mustWork=TRUE)
cmd = paste("rm -fr", remove1, remove2, remove3)
ezSystem(cmd)
