---
title: "`r if (exists('reportTitle')) reportTitle else 'SUSHI Report'`"
output: 
  html_document:
    self_contained: true
    includes:
      in_header: !expr system.file("templates/fgcz_header.html", package="ezRun")
    css: !expr system.file("templates/fgcz.css", package="ezRun")
editor_options: 
  chunk_output_type: inline
---

```{r setup Dmrseq, include=FALSE}
library(dmrseq)
library(rtracklayer)
library(ChIPpeakAnno)
library(ezRun)
library(patchwork)
library(kableExtra)
```

```{r prepare data dmrseq, include=FALSE}
param <- readRDS('param.rds')

gtf <- import(param$ezRef@refFeatureFile)
gtf <- gtf[gtf$type == 'gene',]
gtf <- gtf[gtf$gene_biotype == 'protein_coding',]
names(gtf) <- gtf$gene_id
param$genesAnnotFile <- file.path(dirname(param$ezRef@refFeatureFile),'genes_annotation_byGene.txt')
genesAnnot <- ezRead.table(param$genesAnnotFile, row.names = NULL)
genesAnnot <- genesAnnot[,c('gene_id', 'gene_name','description')]

#Explore results:
bismarkBSseq_filtered <- readRDS("bismarkBSseq_filtered.rds")
regions <- readRDS("dmrseq_results.rds")
blocks <- readRDS("large_blocks.rds")
```

# {.tabset}

## Settings
```{r setting, echo=FALSE}
settings = character()
#settings["Reference:"] = param$refBuild
settings["GroupingColumn:"] = param$grouping
settings["sampleGroup:"] = param$sampleGroup
settings["refGroup:"] = param$refGroup
settings["qValue threshold:"] = param$qval

kable(settings, row.names=TRUE, 
      col.names="Setting", format="html") %>%
  kable_styling(bootstrap_options = "striped", full_width = F,
                position = "left")
```

`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`


## Data Files

```{r write data files, include=FALSE}
##Candidates annotated regions/blocks
# Exploring Significant Regions
regions <- regions[!is.na(regions$beta),]
sigRegions <- regions[regions$qval <= param$qval, ]
numSigRegions <- sum(regions$qval <= param$qval)

# Exploring Significant Blocks
blocks <- blocks[!is.na(blocks$beta),]
sigBlocks <- blocks[blocks$qval <= param$qval, ]
numSigBlocks <- sum(blocks$qval <= param$qval)

# Annotate significant regions/blocks
asigRegions <- data.frame(annotatePeakInBatch(sigRegions,featureType = 'TSS', AnnotationData = gtf))
asigRegions <- merge(asigRegions, genesAnnot, by.x = 'feature', by.y = 'gene_id', all.x = TRUE)
asigRegions <- asigRegions[order(asigRegions$pval),]
cols <- colnames(asigRegions)
cols <- cols[!(cols %in% c('index.start','index.end','index.width','peak'))]
asigRegions <- asigRegions[,cols]

asigBlocks <- data.frame(annotatePeakInBatch(sigBlocks,featureType = 'TSS', AnnotationData = gtf))
asigBlocks <- merge(asigBlocks, genesAnnot, by.x = 'feature', by.y = 'gene_id', all.x = TRUE)
asigBlocks <- asigBlocks[order(asigBlocks$pval),]
cols <- colnames(asigBlocks)
cols <- cols[!(cols %in% c('index.start','index.end','index.width','peak'))]
asigBlocks <- asigBlocks[,cols]

# Export the significant regions to CSV
writexl::write_xlsx(asigRegions,"significantRegions.xlsx")
writexl::write_xlsx(asigBlocks,"significantBlocks.xlsx")
```
### Candidate regions/blocks

[significantRegions.xlsx](significantRegions.xlsx)

[significantBlocks.xlsx](significantBlocks.xlsx)

### Full result objects for regions and blocks as RDS files

[bismarkBSseq_filtered.rds](bismarkBSseq_filtered.rds)

[dmrseq_results.rds](dmrseq_results.rds)

[large_blocks.rds](large_blocks.rds)


## Differential Analyis Plots
```{r count statistics, echo=FALSE, fig.width=12, fig.height=6, message=FALSE, warning=FALSE}
myBoxplot <- function(vec, myTitle){
q <- quantile(vec, probs = c(0.05, 0.95))
vec <- vec[vec >= q[1] & vec <= q[2]]

below_zero <- sum(vec < 0)
above_zero <- sum(vec > 0)
total <- length(vec)
below_zero_percent <- below_zero / total * 100
above_zero_percent <- above_zero / total * 100

boxplot(vec, main = myTitle, horizontal = TRUE, col = "lightblue")
range_x <- par("usr")[1:2]
mid_y <- 1
text(range_x[1]+0.2 * diff(range_x), mid_y-0.5, 
     labels = paste0("Hypomethylation: ", below_zero, " (", round(below_zero_percent, 1), "%)"), 
     adj = c(0, 0.5), col = "red")
text(range_x[2]-0.2 * diff(range_x), mid_y+0.5, 
     labels = paste0("Hypermethylation: ", above_zero, " (", round(above_zero_percent, 1), "%)"), 
     adj = c(1, 0.5), col = "blue")
}

p1 <- myBoxplot(sigRegions$stat,'Hypo- and Hypermethylation of candidate regions')
p2 <- myBoxplot(sigBlocks$stat, 'Hypo- and Hypermethylation of candidate blocks')
par(mfrow = c(1, 2))
p1
p2

```

## QC Plots
```{r count statistics1, echo=FALSE, fig.width=12, fig.width=5, message=FALSE, warning=FALSE}
##global plots
# Plot methylation distribution
p1 <- plotEmpiricalDistribution(bismarkBSseq_filtered, testCovariate = "Condition")
p1
```

```{r count statistics2, echo=FALSE, fig.width=12, fig.width=7, message=FALSE, warning=FALSE}
# Plot coverage distribution
p2 <- plotEmpiricalDistribution(bismarkBSseq_filtered, testCovariate = "Condition", type = "Cov", bySample = TRUE)
p2
```

## Annotation Details
```{r annot, echo=FALSE, fig.width=12, fig.height=6, message=FALSE, warning=FALSE}
#asigRegions
#show 
```

## SessionInfo
```{r, echo=FALSE}
format(Sys.time(), '%Y-%m-%d %H:%M:%S')
ezSessionInfo()
```