---
title: "`r paste('Mothur data analysis report')`"
author: "Functional Genomics Center Zurich"
output: 
  html_document:
    self_contained: false
    includes:
      in_header: fgcz_header.html
    css: fgcz.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
## This report requires output files form the DataAnalysis App

debug <- FALSE
setEnvironments("phantomjs")
```

```{r prepare data, include=FALSE}
### raw data summary tables
summaryTablesToReport <- grep("Summary",names(listOfListAllFiles), value = T)
summaryTablesToReport <- grep("stepConvergence", summaryTablesToReport, invert = T, value = T)
summaryTablesToReport <- listOfListAllFiles[summaryTablesToReport]

finalListOfSummaryTables <- imap(summaryTablesToReport,function(x,y)
  createSummaryTableForKableExtra(x))

### stepsData
convStepTableToReport <- imap(listOfListAllFiles["stepConvergenceSummary"], function(x,y) createStepConvTableForKableExtra(x))

### OTU saturation plots
otuSaturPlotToReport <- otuSaturationPlot(listOfListAllFiles["OTUsCountTable"]$OTUsCountTable)

### OTU saturation table 
otuSaturationTableToReport <- imap(listOfListAllFiles["OTUsCountTable"], function(x,y) createSaturationTableForKableExtra(x)) 

### Chimera plot
chimeraPlotsToReport <- chimeraSummaryPlot(listOfListAllFiles["ChimeraPlot"]$ChimeraPlot)
```

Started on `r format(Sys.time(), "%Y-%m-%d %H:%M:%S")`

## Data pre-processing {.tabset}

### Summary of the raw reads
```{r RawDataSummary, echo=FALSE}
kable(finalListOfSummaryTables["RawDataSummary"]$RawDataSummary$mergedTable, escape=TRUE, row.names=FALSE, format="html") %>%
  kable_styling(bootstrap_options = c("striped", "bordered"),
                full_width = T) %>%
  group_rows(index = finalListOfSummaryTables["RawDataSummary"]$RawDataSummary$aboveHeader) %>%
  scroll_box(width = "100%", height = "600px")
```

### Summary of the deduplicated reads
```{r DeduppedSummary, echo=FALSE}
kable(finalListOfSummaryTables["DeduppedSummary"]$DeduppedSummary$mergedTable, escape=TRUE, row.names=FALSE, format="html") %>%
  kable_styling(bootstrap_options = c("striped", "bordered"),
                full_width = T) %>%
  group_rows(index = finalListOfSummaryTables["DeduppedSummary"]$DeduppedSummary$aboveHeader) %>%
  scroll_box(width = "100%", height = "600px")
```

### Summary of the reads filtered by length and homopolymers
```{r LenAndHomopSummary, echo=FALSE}
kable(finalListOfSummaryTables["LenAndHomopSummary"]$LenAndHomopSummary$mergedTable, escape=TRUE, row.names=FALSE, format="html") %>%
  kable_styling(bootstrap_options = c("striped", "bordered"),
                full_width = T) %>%
  group_rows(index = finalListOfSummaryTables["LenAndHomopSummary"]$LenAndHomopSummary$aboveHeader) %>%
  scroll_box(width = "100%", height = "600px")
```

### Summary of the  reads filtered by mapping
```{r MapFiltSummary, echo=FALSE}
kable(finalListOfSummaryTables["MapFiltSummary"]$MapFiltSummary$mergedTable, escape=TRUE, row.names=FALSE, format="html") %>%
  kable_styling(bootstrap_options = c("striped", "bordered"),
                full_width = T) %>%
  group_rows(index = finalListOfSummaryTables["MapFiltSummary"]$MapFiltSummary$aboveHeader) %>%
  scroll_box(width = "100%", height = "600px")
```

### Summary of the reads preclustered and filtered for chimeras
```{r PreClusteredAndChimeraSummary, echo=FALSE,eval = FALSE}
kable(finalListOfSummaryTables["PreClusteredAndChimeraSummary"]$PreClusteredAndChimeraSummary$mergedTable, escape=TRUE, row.names=FALSE, format="html") %>%
  kable_styling(bootstrap_options = c("striped", "bordered"),
                full_width = T) %>%
  group_rows(index = finalListOfSummaryTables["PreClusteredAndChimeraSummary"]$PreClusteredAndChimeraSummary$aboveHeader) %>%
  scroll_box(width = "100%", height = "600px")
```

```{r,echo=FALSE, out.width="100%"}
  plot(chimeraPlotsToReport)
```

### OTUs convergence summary
```{r stepConvergence, echo=FALSE}
kable(convStepTableToReport["stepConvergenceSummary"]$stepConvergenceSummary$mergedTable, escape=TRUE, row.names=FALSE, format="html") %>%
  kable_styling(bootstrap_options = c("striped", "bordered"),
                full_width = T) %>%
  group_rows(index = convStepTableToReport["stepConvergenceSummary"]$stepConvergenceSummary$aboveHeader) %>%
  scroll_box(width = "100%", height = "600px")
```

### OTUs saturation tables and plots
```{r otuSaturPlot, echo=FALSE, eval = FALSE}
kable(otuSaturationTableToReport["OTUsCountTable"]$OTUsCountTable$mergedTable, escape=TRUE, row.names=FALSE, format="html") %>%
  kable_styling(bootstrap_options = c("striped", "bordered"),
                full_width = T) %>%
  group_rows(index = otuSaturationTableToReport["OTUsCountTable"]$OTUsCountTable$aboveHeader) %>%
  scroll_box(width = "100%", height = "600px")
```

```{r,echo=FALSE, out.width="100%"}
  plot(otuSaturPlotToReport)
```