---
title: "`r paste('Mothur Data Clean')`"
author: "Functional Genomics Center Zurich"
output: 
  html_document:
    self_contained: false
    includes:
      in_header: fgcz_header.html
    css: fgcz.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
## This report requires summary files form mothur

require(knitr)
require(kableExtra)
require(SummarizedExperiment)
require(webshot)
require(htmlwidgets)
debug <- FALSE
setEnvironments("phantomjs")
```

```{r prepare data, include=FALSE}
### rawDataSummary 
rawSummaryTablePacbio <- createSummaryTable(rawPacbio)
lengthDeduppedSummaryTablePacbio <- createSummaryTable(lengthDeduppedPacbio)
mappedAndHomopFilteredSummaryTablePacbio <- createSummaryTable(mappedAndHomopFilteredPacbio)
preClusteredAndChimeraFilteredSummaryTablePacbio <- createSummaryTable(preClusteredAndChimeraFilteredPacbio)

rawSummaryTableIllumina <- createSummaryTable(rawIllumina)
lengthDeduppedSummaryTableIllumina <- createSummaryTable(lengthDeduppedIllumina)
mappedAndHomopFilteredSummaryTableIllumina <- createSummaryTable(mappedAndHomopFilteredIllumina)
preClusteredAndChimeraFilteredSummaryTableIllumina <- createSummaryTable(preClusteredAndChimeraFilteredIllumina)

```

Started on `r format(Sys.time(), "%Y-%m-%d %H:%M:%S")`

## Error estimates and OTUs clustering {.tabset}

### Summary of the raw reads
#### PacBio
```{r sumPB, echo=FALSE}
kable(rawSummaryTablePacbio,row.names=TRUE,  
      col.names=colnames(rawSummaryTablePacbio),format="html") %>%
kable_styling(bootstrap_options = "striped", full_width = F,
                position = "left")
```

#### Illumina
```{r sumIll, echo=FALSE}
kable(rawSummaryTableIllumina, row.names=TRUE, 
      col.names=colnames(rawSummaryTableIllumina), format="html") %>%
  kable_styling(bootstrap_options = "striped", full_width = F,
                position = "left")
```

### Reads filtered by length and duplication
#### PacBio
```{r filtPB, echo=FALSE}
kable(lengthDeduppedSummaryTablePacbio, row.names=TRUE, 
      col.names=colnames(lengthDeduppedSummaryTablePacbio), format="html") %>%
  kable_styling(bootstrap_options = "striped", full_width = F,
                position = "left")
```

#### Illumina
```{r filtIll, echo=FALSE}
kable(lengthDeduppedSummaryTableIllumina, row.names=TRUE, 
      col.names=colnames(lengthDeduppedSummaryTableIllumina), format="html") %>%
  kable_styling(bootstrap_options = "striped", full_width = F,
                position = "left")
```

### Reads filtered by mapping coordinates and Homopolymers
#### PacBio
```{r mapPB, echo=FALSE}
kable(mappedAndHomopFilteredSummaryTablePacbio, row.names=TRUE, 
      col.names=colnames(preClusteredAndChimeraFilteredSummaryTablePacbio), format="html") %>%
  kable_styling(bootstrap_options = "striped", full_width = F,
                position = "left")
```

#### Illumina
```{r mapIll, echo=FALSE}
kable(mappedAndHomopFilteredSummaryTableIllumina, row.names=TRUE, 
      col.names=colnames(preClusteredAndChimeraFilteredSummaryTablePacbio), format="html") %>%
  kable_styling(bootstrap_options = "striped", full_width = F,
                position = "left")
```

### Reads preclusterd and filtered for chimeras
#### PacBio
```{r precPB, echo=FALSE}
kable(preClusteredAndChimeraFilteredSummaryTablePacbio, row.names=TRUE, 
      col.names=colnames(preClusteredAndChimeraFilteredSummaryTablePacbio), format="html") %>%
  kable_styling(bootstrap_options = "striped", full_width = F,
                position = "left")
```

#### Illumina
```{r precIll, echo=FALSE}
kable(preClusteredAndChimeraFilteredSummaryTableIllumina, row.names=TRUE, 
      col.names=colnames(preClusteredAndChimeraFilteredSummaryTableIllumina), format="html") %>%
  kable_styling(bootstrap_options = "striped", full_width = F,
                position = "left")
```

### SessionInfo
```{r, echo=FALSE}
sessionInfo()
```
