---
title: "`r paste('Mothur Data Clean')`"
author: "Functional Genomics Center Zurich"
output: 
  html_document:
    self_contained: false
    includes:
      in_header: fgcz_header.html
    css: fgcz.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
## This report requires summary files form mothur
debug <- FALSE
setEnvironments("phantomjs")
```

```{r}
isGroupThere <- param$Group
```

```{r prepAbund, include=FALSE}
### create plots: 1. abundance
abundPlot <- plot_bar(physeqFullObject, "Group", "Abundance", "Phylum") + geom_bar(aes(color=Phylum, fill=Phylum), stat="identity", position="stack")
```

```{r prepOrdTaxa, include=FALSE, eval=isGroupThere}
### create plots: 2. ordination by taxa 
ordinateDS <- ordinate(physeqFullObject, "NMDS", "bray")
plotOrdTaxa = plot_ordination(physeqFullObject, ordinateDS, type="taxa", color="Phylum") + facet_wrap(~Phylum, 3) + ggtitle("Taxa ordination")
```

```{r prepOrdSamples, include=FALSE, eval = isGroupThere}
### create plots: 2. ordination by samlpe
inputData <- physeqFullObject@otu_table@.Data
inputGroup <- physeqFullObject@sam_data$Group
plotOrdSamples =  pcaForPhylotseqPlot(inputData,inputGroup) + ggtitle("Sample ordination")
```

```{r prepRich, include=FALSE}
### create plots: 3. richness 
if (isGroupThere) {
plotRichness <- plot_richness(physeqFullObject, x="Group", measures=c("Simpson", "Shannon"), color="Group")
}else{
plotRichness <- plot_richness(physeqFullObject, measures=c("Simpson", "Shannon"))
}
```

```{r prepTree, include=FALSE}
### create plots: 4. tree
if (isGroupThere) {
plotTree <- plot_tree(physeqFullObject , ladderize="left", color="Group")
}else{
plotTree <- plot_tree(physeqFullObject , ladderize="left")
}
```

```{r prepHeat, include=FALSE}
### create plots:5. heatmap
inputData <- physeqFullObject@otu_table@.Data
plotHeatmap <- heatmapForPhylotseqPlot(inputData)
```


```{r prepDeSeq, include=FALSE, eval = isGroupThere}
### 6: compare groups
deseqResults <- phyloSeqToDeseq2_tableAndPlots(physeqFullObject)
```

Started on `r format(Sys.time(), "%Y-%m-%d %H:%M:%S")`

## Data pre-processing {.tabset}

### Abundance barplots
#### Illumina
```{r abund, echo=FALSE}
plot(abundPlot)
```

### Ordination plots
```{r ordinTaxa, echo=FALSE,eval = isGroupThere}
plot(plotOrdTaxa)
```
```{r ordinSamples, echo=FALSE, eval = isGroupThere}
plot(plotOrdSamples)
```

### Richness plots
```{r richPB, echo=FALSE}
plot(plotRichness)
```

### Tree plots
```{r treePB, echo=FALSE}
plot(plotTree)
```

### Heatmaps
```{r heatPB, echo=FALSE}
plotHeatmap()
```

### Two-goups comparison
#### Volcano plot
```{r volcano, echo=FALSE,eval = isGroupThere}
plot(deseqResults$vPlot)
```

#### Log-fold changes 
```{r logfold, echo=FALSE,eval = isGroupThere}
plot(deseqResults$logPlot)
```

#### Summary table
```{r table, echo=FALSE,eval = isGroupThere}
plot(deseqResults$table)
```

### SessionInfo
```{r, echo=FALSE}
sessionInfo()
```
