---
title: "`r if (exists('reportTitle')) reportTitle else 'SUSHI Report'`"
output: 
  html_document:
    mathjax: https://fgcz-gstore.uzh.ch/reference/mathjax.js
    self_contained: true
    includes:
      in_header: !expr system.file("templates/fgcz_header.html", package="ezRun")
    css: !expr system.file("templates/fgcz.css", package="ezRun")
editor_options: 
  chunk_output_type: inline
---

# {.tabset}


    
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE, message=FALSE, out.width = "49%")
## This report requires the samsa2 output files generated by the Samsa2 App
debug <- FALSE
library(DESeq2)
library(ggplot2)
library(scales)
library(reshape2)
library(knitr)
library(vegan)
library(pheatmap)
```

```{r}
library(ezRun)
param <- ezLoadRobj("param")
org_Shannon_Simpson <- ezLoadRobj("org_Shannon_Simpson")
func_Shannon_Simpson <- ezLoadRobj("func_Shannon_Simpson")
org_div_graph <- ezLoadRobj("org_div_graph")
func_div_graph <- ezLoadRobj("func_div_graph")
org_PCA <- ezLoadRobj("org_PCA")
func_PCA <- ezLoadRobj("func_PCA")
org_heatmap <- ezLoadRobj("org_heatmap")
func_heatmap <- ezLoadRobj("func_heatmap")
org_combined <- ezLoadRobj("org_combined")
func_combined <- ezLoadRobj("func_combined")
org_volcano <- ezLoadRobj("org_volcano")
func_volcano <- ezLoadRobj("func_volcano")
org_deseq_results <- ezLoadRobj("org_deseq_results")
func_deseq_results <- ezLoadRobj("func_deseq_results")
```


## Diversity
`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`

### Lineage diversity
```{r echo=FALSE}
show(org_Shannon_Simpson)
```


```{r out.height = "660px", out.width='800px', echo=F}
plot(org_div_graph)
```

### Functional diversity
```{r echo=FALSE}
show(func_Shannon_Simpson)
```


```{r out.height = "660px", out.width='800px', echo=F}
plot(func_div_graph)
```

## Differences in lineage-level transcript abundance

```{r out.height = "660px", out.width='800px', echo=F}
plot(org_PCA)
```

```{r out.height = "660px", out.width='800px', echo=F}
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
pheatmap(org_heatmap, 
         cellwidth = 5, 
         cellheight = 5,
         treeheight_row = 40,
         treeheight_col = 40, 
         fontsize = 5, 
         cex = 1)
```

```{r out.height = "660px", out.width='800px', echo=F}
org_combined
```

```{r out.height = "660px", out.width='800px', echo=F}
plot(org_volcano)
```


```{r echo=FALSE}
table <- org_deseq_results[order(org_deseq_results$log2FoldChange,decreasing=TRUE),]
ezInteractiveTableRmd(table[1:10,])
```


```{r echo=FALSE}
table <- org_deseq_results[org_deseq_results$pvalue < 0.05,]
table <- table[order(table$log2FoldChange),]
ezInteractiveTableRmd(table[1:10,])
```


## Differences in functional-level transcript abundance

```{r out.height = "660px", out.width='800px', echo=F}
plot(func_PCA)
```

```{r out.height = "660px", out.width='800px', echo=F}
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
pheatmap(func_heatmap, 
         cellwidth = 5, 
         cellheight = 5,
         treeheight_row = 40,
         treeheight_col = 40, 
         fontsize = 5, 
         cex = 1)
```

```{r out.height = "660px", out.width='800px', echo=F}
func_combined
```

```{r out.height = "660px", out.width='800px', echo=F}
plot(func_volcano)
```


```{r echo=FALSE}
table <- func_deseq_results[order(func_deseq_results$log2FoldChange,decreasing=TRUE),]
ezInteractiveTableRmd(table[1:10,])
```


```{r echo=FALSE}
table <- func_deseq_results[func_deseq_results$pvalue < 0.05,]
table <- table[order(table$log2FoldChange),]
ezInteractiveTableRmd(table[1:10,])
```