---
title:  "`r param$name`"
author: "Functional Genomics Center Zurich"
output: 
  html_document:
    self_contained: false
    includes:
      in_header: fgcz_header.html
    css: fgcz.css
editor_options: 
  chunk_output_type: console
---

Started on `r format(Sys.time(), "%Y-%m-%d %H:%M:%S")`

```{r setup, include=FALSE}
library(ezRun)
library(cowplot)
library(SingleCellExperiment)
library(batchelor)
library(BiocSingular)
library(scater)
library(scran)
# input for this report: sceURLs, param

## debug
sceURLs <- c("wt_3_M"="https://fgcz-sushi.uzh.ch/projects/p2860/SCScran_37216_2019-06-13--13-43-26/wt_3_M_SCScran/00index.html",
             "wt_4_F"="https://fgcz-sushi.uzh.ch/projects/p2860/SCScran_37216_2019-06-13--13-43-26/wt_4_F_SCScran/00index.html")
## end of debug

sceList <- file.path("/srv/gstore/projects",
                     sub("https://fgcz-(gstore|sushi).uzh.ch/projects/", "",
                         dirname(sceURLs)))
sceList <- sapply(sceList, list.files, pattern="sce.*\\.rds", full.names=TRUE)
sceList <- lapply(sceList, readRDS)
names(sceList) <- names(sceURLs)
```

## Integration analysis {.tabset}

### Clustering of integrated samples

```{r Feature selection across batches, echo=FALSE}
decList <- lapply(sceList, function(x){metadata(x)$dec})
decList <- lapply(decList, function(x){x[order(x$bio, decreasing = TRUE), ]})
universe <- Reduce(intersect, lapply(decList, rownames))
bioMatrix <- do.call(cbind, lapply(decList, function(x){x[universe, "bio"]}))
mean.bio <- rowMeans(bioMatrix)
chosen <- universe[mean.bio > 0]
```

`r length(chosen)` features are selected across samples for integration and correction.

```{r multiBatchNorm, echo=FALSE}
rescaled <- do.call(batchelor::multiBatchNorm,
                    lapply(sceList, function(x){x[universe, ]}))
if(param$batchCorrection == "MNN"){
  set.seed(100)
  ## k may need some optimisation
  mnn.out <- do.call(batchelor::fastMNN,
                     c(lapply(rescaled, function(x){x[chosen, ]}),
                       k=20, d=50, BSPARAM=IrlbaParam(deferred=TRUE))
                     )
  sce <- mnn.out
  assay(sce, "counts") <- do.call(cbind,
                                    lapply(rescaled,
                                           function(x){assay(x[chosen, ], "counts")}))
  assay(sce, "logcounts") <- do.call(cbind,
                                    lapply(rescaled,
                                           function(x){assay(x[chosen, ], "logcounts")}))
}else{
  stop("Not implemented yet!")
  foo <- multiBatchPCA(rescaled[[1]], rescaled[[2]], d=50, BSPARAM=IrlbaParam(deferred=TRUE))
  sce <- do.call(cbind, lapply(rescaled, function(x){x[chosen, ]}))
}
```

#### Visualization on low-dimensional space

```{r tsne, echo=FALSE}
# Using irlba to set up the t-SNE, for speed.
set.seed(100)
osce <- runPCA(sce, ntop=Inf, BSPARAM=IrlbaParam())
osce <- runTSNE(osce, use_dimred="PCA")
ot <- plotTSNE(osce, colour_by="batch") + ggtitle("Original")

# Corrected.
set.seed(100)
sce <- runTSNE(sce, use_dimred="corrected")
ct <- plotTSNE(sce, colour_by="batch") + ggtitle("Corrected")

p1 <- plotTSNE(osce, by_exprs_values="logcounts", colour_by=eachMarker) +
  scale_fill_gradient(low="gray", high="red") + 
  ggtitle(eachMarker) + labs(fill=eachMarker)
p1

p2 <- plotTSNE(sce, by_exprs_values="reconstructed", colour_by=eachMarker) +
  scale_fill_gradient(low="gray", high="red") +
  ggtitle(eachMarker) + labs(fill=eachMarker)
p2

p <- plot_grid(ot, ct, p1, p2, ncol=2)
save_plot(filename="OriginalVsCorrected.pdf", p, ncol=2, nrow=2,
          base_height = 7)


# p3 <- plotTSNE(sceList[[1]], colour_by=eachMarker) +
#   scale_fill_gradient(low="gray", high="red") + 
#   ggtitle(eachMarker) + labs(fill=eachMarker)
# p3

multiplot(ot, ct, p1, p2, cols=2)
```


