---
title: "`r if (exists('reportTitle')) reportTitle else 'SUSHI Report'`"
output: 
  html_document:
    mathjax: https://fgcz-gstore.uzh.ch/reference/mathjax.js
    self_contained: true
    includes:
      in_header: !expr system.file("templates/fgcz_header.html", package="ezRun")
    css: !expr system.file("templates/fgcz.css", package="ezRun")
editor_options: 
  chunk_output_type: inline
---

# {.tabset}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(magrittr)
```


## Number of SNPs
`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`

```{r SNP counts, fig.width=8, fig.height=5, echo=FALSE, message=FALSE, warning=FALSE}
data <- read.table(snp_counts, sep="\t", skip=2)
names(data) <- c("Counts", "Sample")
samples <- gsub("samples/", "", data$Sample)
plot_ly(data, x = samples, y = data$Counts)
```

## Private/Shared SNPs

```{r Private SNPs, fig.width=8, fig.height=5, echo=FALSE, message=FALSE, warning=FALSE}
data <- read.table(private_snp_counts, sep="\t", skip=1)
names(data) <- c("Private_SNPs", "Sample")
fig <- plot_ly(data, x = ~Sample, y = ~Private_SNPs, type = 'bar', name = 'Private SNPs')
fig <- fig %>% layout(title = 'Private SNPs', yaxis = list(title = 'Count'), xaxis=list(title=''))
fig
```

```{r Shared SNPs, fig.width=8, fig.height=5, echo=FALSE, message=FALSE, warning=FALSE}
data <- read.table(shared_snp_counts, sep="\t", skip=1)
names(data) <- c("Shared_SNPs", "Count")
fig <- plot_ly(data, x = ~Shared_SNPs, y = ~Count, type = 'bar', name = 'Shared SNPs')
fig <- fig %>% layout(title = 'Shared SNPs', yaxis = list(title = 'Count'), xaxis=list(title='Number of shared SNPs'))
fig
```

## Transisions/Transversions

```{r tstv, fig.width=8, fig.height=5, echo=FALSE, message=FALSE, warning=FALSE}
data <- read.table(tstv, sep="\t", skip=1)
names(data) <- c("Transisions", "Transversions", "tstv", "Sample")
fig <- plot_ly(data, x = ~Sample, y = ~tstv, type = 'bar', name = 'Transisions/Transversions')
fig <- fig %>% layout(yaxis = list(title = 'ts/tv'), xaxis=list(title=''))
fig
```

## Input Dataset
```{r, echo=FALSE, message=FALSE}
ezInteractiveTableRmd(values=ans4Report[["dataset"]])
```

## SessionInfo
```{r, echo=FALSE}
ezSessionInfo()
```
